@baseUri = http://127.0.0.1:8013/api 

### generate cover
POST {{baseUri}}/gen-cover
Content-Type: application/json

{
    "description": "celebrate the new year with my family"
}

### get covers
POST {{baseUri}}/get-covers
Content-Type: application/json

{
    
}